// act_lut_rom.sv — AUTO-GENERATED by verify/gen_act_lut.py
// Piecewise-linear LUT for GeLU / SiLU (64 segments, x in [-8, 8], Q16.16)

`timescale 1ns / 1ps

module act_lut_rom #(
    parameter int SEGMENTS = 64,
    parameter int SEG_W    = 6,
    parameter int Q_W      = 32,
    parameter int LUT_W    = 32
) (
    input  logic [1:0]              act_mode,
    input  logic [SEG_W-1:0]        seg_idx,
    output logic signed [LUT_W-1:0] y_base,
    output logic signed [LUT_W-1:0] slope
);

    localparam int ACT_GELU = 2'd1;
    localparam int ACT_SILU = 2'd2;

    logic signed [LUT_W-1:0] gelu_y [SEGMENTS];
    logic signed [LUT_W-1:0] gelu_m [SEGMENTS];
    logic signed [LUT_W-1:0] silu_y [SEGMENTS];
    logic signed [LUT_W-1:0] silu_m [SEGMENTS];

    assign gelu_y[0] = 32'sd0;
    assign gelu_y[1] = 32'sd0;
    assign gelu_y[2] = 32'sd0;
    assign gelu_y[3] = 32'sd0;
    assign gelu_y[4] = 32'sd0;
    assign gelu_y[5] = 32'sd0;
    assign gelu_y[6] = 32'sd0;
    assign gelu_y[7] = 32'sd0;
    assign gelu_y[8] = 32'sd0;
    assign gelu_y[9] = 32'sd0;
    assign gelu_y[10] = 32'sd0;
    assign gelu_y[11] = 32'sd0;
    assign gelu_y[12] = 32'sd0;
    assign gelu_y[13] = 32'sd0;
    assign gelu_y[14] = 32'sd0;
    assign gelu_y[15] = 32'sd4294967295;
    assign gelu_y[16] = 32'sd4294967291;
    assign gelu_y[17] = 32'sd4294967282;
    assign gelu_y[18] = 32'sd4294967256;
    assign gelu_y[19] = 32'sd4294967193;
    assign gelu_y[20] = 32'sd4294967058;
    assign gelu_y[21] = 32'sd4294966790;
    assign gelu_y[22] = 32'sd4294966307;
    assign gelu_y[23] = 32'sd4294965513;
    assign gelu_y[24] = 32'sd4294964321;
    assign gelu_y[25] = 32'sd4294962695;
    assign gelu_y[26] = 32'sd4294960714;
    assign gelu_y[27] = 32'sd4294958627;
    assign gelu_y[28] = 32'sd4294956888;
    assign gelu_y[29] = 32'sd4294956152;
    assign gelu_y[30] = 32'sd4294957185;
    assign gelu_y[31] = 32'sd4294960721;
    assign gelu_y[32] = 32'sd0;
    assign gelu_y[33] = 32'sd9809;
    assign gelu_y[34] = 32'sd22657;
    assign gelu_y[35] = 32'sd38008;
    assign gelu_y[36] = 32'sd55128;
    assign gelu_y[37] = 32'sd73251;
    assign gelu_y[38] = 32'sd91722;
    assign gelu_y[39] = 32'sd110087;
    assign gelu_y[40] = 32'sd128097;
    assign gelu_y[41] = 32'sd145673;
    assign gelu_y[42] = 32'sd162851;
    assign gelu_y[43] = 32'sd179718;
    assign gelu_y[44] = 32'sd196370;
    assign gelu_y[45] = 32'sd212889;
    assign gelu_y[46] = 32'sd229336;
    assign gelu_y[47] = 32'sd245746;
    assign gelu_y[48] = 32'sd262139;
    assign gelu_y[49] = 32'sd278527;
    assign gelu_y[50] = 32'sd294912;
    assign gelu_y[51] = 32'sd311296;
    assign gelu_y[52] = 32'sd327680;
    assign gelu_y[53] = 32'sd344064;
    assign gelu_y[54] = 32'sd360448;
    assign gelu_y[55] = 32'sd376832;
    assign gelu_y[56] = 32'sd393216;
    assign gelu_y[57] = 32'sd409600;
    assign gelu_y[58] = 32'sd425984;
    assign gelu_y[59] = 32'sd442368;
    assign gelu_y[60] = 32'sd458752;
    assign gelu_y[61] = 32'sd475136;
    assign gelu_y[62] = 32'sd491520;
    assign gelu_y[63] = 32'sd507904;

    assign gelu_m[0] = 32'sd0;
    assign gelu_m[1] = 32'sd0;
    assign gelu_m[2] = 32'sd0;
    assign gelu_m[3] = 32'sd0;
    assign gelu_m[4] = 32'sd0;
    assign gelu_m[5] = 32'sd0;
    assign gelu_m[6] = 32'sd0;
    assign gelu_m[7] = 32'sd0;
    assign gelu_m[8] = 32'sd0;
    assign gelu_m[9] = 32'sd0;
    assign gelu_m[10] = 32'sd0;
    assign gelu_m[11] = 32'sd0;
    assign gelu_m[12] = 32'sd0;
    assign gelu_m[13] = 32'sd4294967295;
    assign gelu_m[14] = 32'sd4294967292;
    assign gelu_m[15] = 32'sd4294967283;
    assign gelu_m[16] = 32'sd4294967257;
    assign gelu_m[17] = 32'sd4294967192;
    assign gelu_m[18] = 32'sd4294967046;
    assign gelu_m[19] = 32'sd4294966754;
    assign gelu_m[20] = 32'sd4294966225;
    assign gelu_m[21] = 32'sd4294965366;
    assign gelu_m[22] = 32'sd4294964120;
    assign gelu_m[23] = 32'sd4294962525;
    assign gelu_m[24] = 32'sd4294960794;
    assign gelu_m[25] = 32'sd4294959373;
    assign gelu_m[26] = 32'sd4294958945;
    assign gelu_m[27] = 32'sd4294960343;
    assign gelu_m[28] = 32'sd4294964352;
    assign gelu_m[29] = 32'sd4130;
    assign gelu_m[30] = 32'sd14146;
    assign gelu_m[31] = 32'sd26300;
    assign gelu_m[32] = 32'sd39236;
    assign gelu_m[33] = 32'sd51390;
    assign gelu_m[34] = 32'sd61406;
    assign gelu_m[35] = 32'sd68480;
    assign gelu_m[36] = 32'sd72489;
    assign gelu_m[37] = 32'sd73887;
    assign gelu_m[38] = 32'sd73459;
    assign gelu_m[39] = 32'sd72038;
    assign gelu_m[40] = 32'sd70307;
    assign gelu_m[41] = 32'sd68712;
    assign gelu_m[42] = 32'sd67466;
    assign gelu_m[43] = 32'sd66607;
    assign gelu_m[44] = 32'sd66078;
    assign gelu_m[45] = 32'sd65786;
    assign gelu_m[46] = 32'sd65640;
    assign gelu_m[47] = 32'sd65575;
    assign gelu_m[48] = 32'sd65549;
    assign gelu_m[49] = 32'sd65540;
    assign gelu_m[50] = 32'sd65537;
    assign gelu_m[51] = 32'sd65536;
    assign gelu_m[52] = 32'sd65536;
    assign gelu_m[53] = 32'sd65536;
    assign gelu_m[54] = 32'sd65536;
    assign gelu_m[55] = 32'sd65536;
    assign gelu_m[56] = 32'sd65536;
    assign gelu_m[57] = 32'sd65536;
    assign gelu_m[58] = 32'sd65536;
    assign gelu_m[59] = 32'sd65536;
    assign gelu_m[60] = 32'sd65536;
    assign gelu_m[61] = 32'sd65536;
    assign gelu_m[62] = 32'sd65536;
    assign gelu_m[63] = 32'sd65536;

    assign silu_y[0] = 32'sd4294967120;
    assign silu_y[1] = 32'sd4294967077;
    assign silu_y[2] = 32'sd4294967024;
    assign silu_y[3] = 32'sd4294966959;
    assign silu_y[4] = 32'sd4294966878;
    assign silu_y[5] = 32'sd4294966779;
    assign silu_y[6] = 32'sd4294966657;
    assign silu_y[7] = 32'sd4294966507;
    assign silu_y[8] = 32'sd4294966324;
    assign silu_y[9] = 32'sd4294966100;
    assign silu_y[10] = 32'sd4294965829;
    assign silu_y[11] = 32'sd4294965500;
    assign silu_y[12] = 32'sd4294965103;
    assign silu_y[13] = 32'sd4294964626;
    assign silu_y[14] = 32'sd4294964056;
    assign silu_y[15] = 32'sd4294963379;
    assign silu_y[16] = 32'sd4294962581;
    assign silu_y[17] = 32'sd4294961649;
    assign silu_y[18] = 32'sd4294960572;
    assign silu_y[19] = 32'sd4294959346;
    assign silu_y[20] = 32'sd4294957972;
    assign silu_y[21] = 32'sd4294956467;
    assign silu_y[22] = 32'sd4294954867;
    assign silu_y[23] = 32'sd4294953236;
    assign silu_y[24] = 32'sd4294951672;
    assign silu_y[25] = 32'sd4294950317;
    assign silu_y[26] = 32'sd4294949363;
    assign silu_y[27] = 32'sd4294949052;
    assign silu_y[28] = 32'sd4294949671;
    assign silu_y[29] = 32'sd4294951527;
    assign silu_y[30] = 32'sd4294954925;
    assign silu_y[31] = 32'sd4294960123;
    assign silu_y[32] = 32'sd0;
    assign silu_y[33] = 32'sd9211;
    assign silu_y[34] = 32'sd20397;
    assign silu_y[35] = 32'sd33383;
    assign silu_y[36] = 32'sd47911;
    assign silu_y[37] = 32'sd63676;
    assign silu_y[38] = 32'sd80371;
    assign silu_y[39] = 32'sd97709;
    assign silu_y[40] = 32'sd115448;
    assign silu_y[41] = 32'sd133396;
    assign silu_y[42] = 32'sd151411;
    assign silu_y[43] = 32'sd169395;
    assign silu_y[44] = 32'sd187284;
    assign silu_y[45] = 32'sd205042;
    assign silu_y[46] = 32'sd222652;
    assign silu_y[47] = 32'sd240113;
    assign silu_y[48] = 32'sd257429;
    assign silu_y[49] = 32'sd274611;
    assign silu_y[50] = 32'sd291672;
    assign silu_y[51] = 32'sd308626;
    assign silu_y[52] = 32'sd325487;
    assign silu_y[53] = 32'sd342268;
    assign silu_y[54] = 32'sd358981;
    assign silu_y[55] = 32'sd375636;
    assign silu_y[56] = 32'sd392244;
    assign silu_y[57] = 32'sd408811;
    assign silu_y[58] = 32'sd425345;
    assign silu_y[59] = 32'sd441851;
    assign silu_y[60] = 32'sd458334;
    assign silu_y[61] = 32'sd474799;
    assign silu_y[62] = 32'sd491248;
    assign silu_y[63] = 32'sd507685;

    assign silu_m[0] = 32'sd4294967125;
    assign silu_m[1] = 32'sd4294967084;
    assign silu_m[2] = 32'sd4294967034;
    assign silu_m[3] = 32'sd4294966973;
    assign silu_m[4] = 32'sd4294966898;
    assign silu_m[5] = 32'sd4294966807;
    assign silu_m[6] = 32'sd4294966697;
    assign silu_m[7] = 32'sd4294966564;
    assign silu_m[8] = 32'sd4294966403;
    assign silu_m[9] = 32'sd4294966210;
    assign silu_m[10] = 32'sd4294965980;
    assign silu_m[11] = 32'sd4294965708;
    assign silu_m[12] = 32'sd4294965388;
    assign silu_m[13] = 32'sd4294965016;
    assign silu_m[14] = 32'sd4294964588;
    assign silu_m[15] = 32'sd4294964105;
    assign silu_m[16] = 32'sd4294963568;
    assign silu_m[17] = 32'sd4294962990;
    assign silu_m[18] = 32'sd4294962389;
    assign silu_m[19] = 32'sd4294961800;
    assign silu_m[20] = 32'sd4294961277;
    assign silu_m[21] = 32'sd4294960898;
    assign silu_m[22] = 32'sd4294960771;
    assign silu_m[23] = 32'sd4294961039;
    assign silu_m[24] = 32'sd4294961876;
    assign silu_m[25] = 32'sd4294963480;
    assign silu_m[26] = 32'sd4294966054;
    assign silu_m[27] = 32'sd2473;
    assign silu_m[28] = 32'sd7425;
    assign silu_m[29] = 32'sd13591;
    assign silu_m[30] = 32'sd20792;
    assign silu_m[31] = 32'sd28693;
    assign silu_m[32] = 32'sd36843;
    assign silu_m[33] = 32'sd44744;
    assign silu_m[34] = 32'sd51945;
    assign silu_m[35] = 32'sd58111;
    assign silu_m[36] = 32'sd63063;
    assign silu_m[37] = 32'sd66778;
    assign silu_m[38] = 32'sd69352;
    assign silu_m[39] = 32'sd70956;
    assign silu_m[40] = 32'sd71793;
    assign silu_m[41] = 32'sd72061;
    assign silu_m[42] = 32'sd71934;
    assign silu_m[43] = 32'sd71555;
    assign silu_m[44] = 32'sd71032;
    assign silu_m[45] = 32'sd70443;
    assign silu_m[46] = 32'sd69842;
    assign silu_m[47] = 32'sd69264;
    assign silu_m[48] = 32'sd68727;
    assign silu_m[49] = 32'sd68244;
    assign silu_m[50] = 32'sd67816;
    assign silu_m[51] = 32'sd67444;
    assign silu_m[52] = 32'sd67124;
    assign silu_m[53] = 32'sd66852;
    assign silu_m[54] = 32'sd66622;
    assign silu_m[55] = 32'sd66429;
    assign silu_m[56] = 32'sd66268;
    assign silu_m[57] = 32'sd66135;
    assign silu_m[58] = 32'sd66025;
    assign silu_m[59] = 32'sd65934;
    assign silu_m[60] = 32'sd65859;
    assign silu_m[61] = 32'sd65798;
    assign silu_m[62] = 32'sd65748;
    assign silu_m[63] = 32'sd65707;

    always_comb begin
        case (act_mode)
            ACT_GELU: begin
                y_base = gelu_y[seg_idx];
                slope  = gelu_m[seg_idx];
            end
            ACT_SILU: begin
                y_base = silu_y[seg_idx];
                slope  = silu_m[seg_idx];
            end
            default: begin
                y_base = '0;
                slope  = '0;
            end
        endcase
    end

endmodule
