#!/usr/bin/env python3
"""Generate piecewise-linear LUT ROM for GeLU / SiLU (VAU hardware)."""

from __future__ import annotations

import math
from pathlib import Path

SEGMENTS = 64
X_MIN = -8.0
X_MAX = 8.0
FRAC_BITS = 16
Q = 1 << FRAC_BITS


def gelu_f(x: float) -> float:
    return x * 0.5 * (1.0 + math.tanh(math.sqrt(2.0 / math.pi) * (x + 0.044715 * x**3)))


def silu_f(x: float) -> float:
    if x > 20:
        return x
    if x < -20:
        return 0.0
    return x / (1.0 + math.exp(-x))


def float_to_q16(v: float) -> int:
    q = int(round(v * Q))
    q = max(-(1 << 31), min((1 << 31) - 1, q))
    return q & 0xFFFFFFFF


def build_lut(fn) -> tuple[list[int], list[int]]:
    """Return (y_base[64], slope[64]) for piecewise linear over [X_MIN, X_MAX]."""
    step = (X_MAX - X_MIN) / SEGMENTS
    y_base: list[int] = []
    slope: list[int] = []
    for i in range(SEGMENTS):
        x0 = X_MIN + i * step
        x1 = x0 + step
        y0 = fn(x0)
        y1 = fn(x1)
        y_base.append(float_to_q16(y0))
        slope.append(float_to_q16((y1 - y0) / step))
    return y_base, slope


def emit_sv(path: Path) -> None:
    gelu_y, gelu_m = build_lut(gelu_f)
    silu_y, silu_m = build_lut(silu_f)

    lines = [
        "// act_lut_rom.sv — AUTO-GENERATED by verify/gen_act_lut.py",
        "// Piecewise-linear LUT for GeLU / SiLU (64 segments, x in [-8, 8], Q16.16)",
        "",
        "`timescale 1ns / 1ps",
        "",
        "module act_lut_rom #(",
        "    parameter int SEGMENTS = 64,",
        "    parameter int SEG_W    = 6,",
        "    parameter int Q_W      = 32,",
        "    parameter int LUT_W    = 32",
        ") (",
        "    input  logic [1:0]              act_mode,",
        "    input  logic [SEG_W-1:0]        seg_idx,",
        "    output logic signed [LUT_W-1:0] y_base,",
        "    output logic signed [LUT_W-1:0] slope",
        ");",
        "",
        "    localparam int ACT_GELU = 2'd1;",
        "    localparam int ACT_SILU = 2'd2;",
        "",
        "    logic signed [LUT_W-1:0] gelu_y [SEGMENTS];",
        "    logic signed [LUT_W-1:0] gelu_m [SEGMENTS];",
        "    logic signed [LUT_W-1:0] silu_y [SEGMENTS];",
        "    logic signed [LUT_W-1:0] silu_m [SEGMENTS];",
        "",
    ]

    for i in range(SEGMENTS):
        lines.append(f"    assign gelu_y[{i}] = 32'sd{gelu_y[i]};")
    lines.append("")
    for i in range(SEGMENTS):
        lines.append(f"    assign gelu_m[{i}] = 32'sd{gelu_m[i]};")
    lines.append("")
    for i in range(SEGMENTS):
        lines.append(f"    assign silu_y[{i}] = 32'sd{silu_y[i]};")
    lines.append("")
    for i in range(SEGMENTS):
        lines.append(f"    assign silu_m[{i}] = 32'sd{silu_m[i]};")
    lines.append("")
    lines += [
        "    always_comb begin",
        "        case (act_mode)",
        "            ACT_GELU: begin",
        "                y_base = gelu_y[seg_idx];",
        "                slope  = gelu_m[seg_idx];",
        "            end",
        "            ACT_SILU: begin",
        "                y_base = silu_y[seg_idx];",
        "                slope  = silu_m[seg_idx];",
        "            end",
        "            default: begin",
        "                y_base = '0;",
        "                slope  = '0;",
        "            end",
        "        endcase",
        "    end",
        "",
        "endmodule",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {path}")


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    emit_sv(root / "rtl" / "activ" / "act_lut_rom.sv")
